# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conf.proto',
  package='v1',
  syntax='proto3',
  serialized_options=b'Z\004.;v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nconf.proto\x12\x02v1\"&\n\x04\x43onf\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2+\n\x0c\x63onfigurator\x12\x1b\n\x03Get\x12\x08.v1.Conf\x1a\x08.v1.Conf\"\x00\x42\x06Z\x04.;v1b\x06proto3'
)




_CONF = _descriptor.Descriptor(
  name='Conf',
  full_name='v1.Conf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='v1.Conf.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='v1.Conf.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['Conf'] = _CONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Conf = _reflection.GeneratedProtocolMessageType('Conf', (_message.Message,), {
  'DESCRIPTOR' : _CONF,
  '__module__' : 'conf_pb2'
  # @@protoc_insertion_point(class_scope:v1.Conf)
  })
_sym_db.RegisterMessage(Conf)


DESCRIPTOR._options = None

_CONFIGURATOR = _descriptor.ServiceDescriptor(
  name='configurator',
  full_name='v1.configurator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=58,
  serialized_end=101,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='v1.configurator.Get',
    index=0,
    containing_service=None,
    input_type=_CONF,
    output_type=_CONF,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGURATOR)

DESCRIPTOR.services_by_name['configurator'] = _CONFIGURATOR

# @@protoc_insertion_point(module_scope)
